spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC???????
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


# ????
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl


